# Generated by Django 4.2.3 on 2023-07-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_qa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('client_data', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
